// export const INIT = "INIT";

// //Auth
// export const AUTH = "AUTH";
// export const AUTH_USER_SET = "AUTH_USER_SET";
// //--USERFLOW--//
// export const SIGNING_UP = "SIGNING_UP";
// export const SIGN_IN_FACEBOOK = "SIGN_IN_FACEBOOK";
// export const SIGN_IN_GOOGLE = "SIGN_IN_GOOGLE";
// export const SIGN_IN_GITHUB = "SIGN_IN_GITHUB";
// export const LOG_OUT = "LOG_OUT";

// //Local State
// export const WIPE_DATA = "WIPE_DATA";
// export const UPDATE_PROFILE = "UPDATE_PROFILE";
// export const UPDATE_PROFILE_LIST = "UPDATE_PROFILE_LIST";
// export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
// export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
// export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
// export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
// export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
// export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

// //Routes
// export const DASHBOARD = "DASHBOARD";

// //USER PROFILE - Themes
// export const CHANGE_THEME_MODE = "CHANGE_THEME_MODE";
// export const CHANGE_THEME_TYPE = "CHANGE_THEME_TYPE";

// //EVENT FORM DATA
// export const ADD_EVENT_LOCATION = "ADD_EVENT_LOCATION";
// export const CANCEL_EVENT_LOCATION = "CANCEL_EVENT_LOCATION";
// export const CREATE_EVENT_DATA = "CREATE_EVENT_DATA";
// export const UPDATE_ACTIVE_EVENT_LOCATION = "UPDATE_ACTIVE_EVENT_LOCATION";
// export const UPDATE_EVENT_LOCATIONS = "UPDATE_EVENT_LOCATIONS";

// //DATE FORM DATA
// export const UPDATE_DATE = "UPDATE_DATE";
// export const UPDATE_EVENT_ASPECT = "UPDATE_EVENT_ASPECT";

// //CATEGORIES FORM DATA
// export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";

// ////==== CRUD ACTIONS ==== ////
// /// --- EVENTS --- ///
// export const LOAD_DATA = "LOAD_DATA";
// export const EVENTS_API_REQUEST = "EVENTS_API_REQUEST";
// export const EVENTS_API_START = "EVENTS_API_START";
// export const EVENTS_API_RESULT = "EVENTS_API_RESULT";

// //--CREATE--//
// export const EVENTS_CREATE_REQUEST = "EVENTS_CREATE_REQUEST";
// export const EVENTS_CREATE_START = "EVENTS_CREATE_START";
// export const EVENTS_CREATE_SUCCESS = "EVENTS_CREATE_SUCCESS";
// export const EVENTS_CREATE_FAILURE = "EVENTS_CREATE_FAILURE";
// //--FETCH--//
// export const EVENTS_FETCH_START = "EVENTS_FETCH_START";
// export const EVENTS_FETCH_SUCCESS = "EVENTS_FETCH_SUCCESS";
// export const EVENTS_FETCH_FEW_START = "EVENTS_FETCH_FEW_START";
// //--FETCH ONE EVENT--//

// export const EVENTS_FETCH_ONE_START = "EVENTS_FETCH_ONE_START";
// export const EVENTS_FETCH_ONE_SUCCESS = "EVENTS_FETCH_ONE_SUCCESS";
// export const EVENTS_FETCH_ONE_FAILURE = "EVENTS_FETCH_ONE_FAILURE";
// //--FETCH EVENT HOST--//
// export const EVENTS_FETCH_HOST_REQUEST = "EVENTS_FETCH_HOST_REQUEST";
// export const EVENTS_FETCH_HOST_START = "EVENTS_FETCH_HOST_START";
// export const EVENTS_FETCH_HOST_SUCCESS = "EVENTS_FETCH_HOST_SUCCESS";
// export const EVENTS_FETCH_HOST_FAILURE = "EVENTS_FETCH_HOST_FAILURE";
// //--UPDATE--//
// export const EVENTS_UPDATE_REQUEST = "EVENTS_UPDATE_REQUEST";
// export const EVENTS_UPDATE_START = "EVENTS_UPDATE_START";
// export const EVENTS_UPDATE_SUCCESS = "EVENTS_UPDATE_SUCCESS";
// export const EVENTS_UPDATE_FAILURE = "EVENTS_UPDATE_FAILURE";
// //--DELETE--//
// export const EVENTS_DELETE_REQUEST = "EVENTS_DELETE_REQUEST";
// export const EVENTS_DELETE_START = "EVENTS_DELETE_START";
// export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS";
// export const EVENTS_DELETE_FAILURE = "EVENTS_DELETE_FAILURE";

// /// --- VENUES --- ///
// export const VENUES_API_REQUEST = "VENUES_API_REQUEST";
// export const VENUES_API_START = "VENUES_API_START";
// export const VENUES_API_RESULT = "VENUES_API_RESULT";
// //--CREATE--//
// export const VENUES_CREATE_REQUEST = "VENUES_CREATE_REQUEST";
// export const VENUES_CREATE_START = "VENUES_CREATE_START";
// export const VENUES_CREATE_SUCCESS = "VENUES_CREATE_SUCCESS";
// export const VENUES_CREATE_FAILURE = "VENUES_CREATE_FAILURE";
// //--FETCH ONE VENUE--//
// export const VENUES_FETCH_ONE_REQUEST = "VENUES_FETCH_ONE_REQUEST";
// export const VENUES_FETCH_ONE_START = "VENUES_FETCH_ONE_START";
// export const VENUES_FETCH_ONE_SUCCESS = "VENUES_FETCH_ONE_SUCCESS";
// export const VENUES_FETCH_ONE_FAILURE = "VENUES_FETCH_ONE_FAILURE";
// //--FETCH ALL VENUES--//
// export const VENUES_FETCH_FEW = "VENUES_FETCH_FEW";
// export const VENUES_FETCH_START = "VENUES_FETCH_START";
// export const VENUES_FETCH_SUCCESS = "VENUES_FETCH_SUCCESS";
// export const VENUES_FETCH_FAILURE = "VENUES_FETCH_FAILURE";
// //--FETCH VENUE OWNER--//
// export const VENUES_FETCH_HOST_REQUEST = "VENUES_FETCH_HOST_REQUEST";
// export const VENUES_FETCH_HOST_START = "VENUES_FETCH_HOST_START";
// export const VENUES_FETCH_HOST_SUCCESS = "VENUES_FETCH_HOST_SUCCESS";
// export const VENUES_FETCH_HOST_FAILURE = "VENUES_FETCH_HOST_FAILURE";
// //--UPDATE--//
// export const VENUES_UPDATE_REQUEST = "VENUES_UPDATE_REQUEST";
// export const VENUES_UPDATE_START = "VENUES_UPDATE_START";
// export const VENUES_UPDATE_SUCCESS = "VENUES_UPDATE_SUCCESS";
// export const VENUES_UPDATE_FAILURE = "VENUES_UPDATE_FAILURE";
// //--DELETE--//
// export const VENUES_DELETE_REQUEST = "VENUES_DELETE_REQUEST";
// export const VENUES_DELETE_START = "VENUES_DELETE_START";
// export const VENUES_DELETE_SUCCESS = "VENUES_DELETE_SUCCESS";
// export const VENUES_DELETE_FAILURE = "VENUES_DELETE_FAILURE";

// /// --- TALENTS --- ///
// //--CREATE--//
// export const TALENTS_CREATE_REQUEST = "TALENTS_CREATE_REQUEST";
// export const TALENTS_CREATE_START = "TALENTS_CREATE_START";
// export const TALENTS_CREATE_SUCCESS = "TALENTS_CREATE_SUCCESS";
// export const TALENTS_CREATE_FAILURE = "TALENTS_CREATE_FAILURE";
// //--FETCH ONE VENUE--//
// export const TALENTS_FETCH_ONE_REQUEST = "TALENTS_FETCH_ONE_REQUEST";
// export const TALENTS_FETCH_ONE_START = "TALENTS_FETCH_ONE_START";
// export const TALENTS_FETCH_ONE_SUCCESS = "TALENTS_FETCH_ONE_SUCCESS";
// export const TALENTS_FETCH_ONE_FAILURE = "TALENTS_FETCH_ONE_FAILURE";
// //--FETCH ALL TALENTS--//
// export const TALENTS_FETCH_START = "TALENTS_FETCH_START";
// export const TALENTS_FETCH_REQUEST = "TALENTS_FETCH_REQUEST";
// export const TALENTS_FETCH_SUCCESS = "TALENTS_FETCH_SUCCESS";
// export const TALENTS_FETCH_FAILURE = "TALENTS_FETCH_FAILURE";
// //--UPDATE--//
// export const TALENTS_UPDATE_REQUEST = "TALENTS_UPDATE_REQUEST";
// export const TALENTS_UPDATE_START = "TALENTS_UPDATE_START";
// export const TALENTS_UPDATE_SUCCESS = "TALENTS_UPDATE_SUCCESS";
// export const TALENTS_UPDATE_FAILURE = "TALENTS_UPDATE_FAILURE";
// //--DELETE--//
// export const TALENTS_DELETE_REQUEST = "TALENTS_DELETE_REQUEST";
// export const TALENTS_DELETE_START = "TALENTS_DELETE_START";
// export const TALENTS_DELETE_SUCCESS = "TALENTS_DELETE_SUCCESS";
// export const TALENTS_DELETE_FAILURE = "TALENTS_DELETE_FAILURE";

// /// --- COMMUNICATIONS (EMAIL & NOTIFICATIONS) --- ///
// export const EMAIL_SEND = "EMAIL_SEND";

// /// --- PAYMENTS --- ///
// export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
// export const PAYMENT_START = "PAYMENT_START";
// export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
// export const PAYMENT_FAILURE = "PAYMENT_FAILURE";
